// data.js - Your complete koi collection
const initialFishData = [
    { id: 1, name: "Ki Utsuri", variety: "Ki Utsuri", length: 43, date: "2025-11-22", status: "alive", notes: "", image: "" },
    { id: 2, name: "Hi", variety: "Black nosed sanke", length: 38, date: "", status: "alive", notes: "", image: "" },
    { id: 3, name: "Tancho", variety: "Goshiki", length: 33, date: "", status: "alive", notes: "", image: "" },
    { id: 4, name: "Unnamed", variety: "Gin Rin Sanke", length: 45, date: "", status: "alive", notes: "", image: "" },
    { id: 5, name: "Pearl", variety: "Shiro Utsuri", length: 60, date: "", status: "alive", notes: "", image: "" },
    { id: 6, name: "Pumkin", variety: "Platinum Ogon", length: 40, date: "", status: "alive", notes: "", image: "" },
    { id: 7, name: "Two Face", variety: "Gin Rin Sanke", length: 46, date: "", status: "alive", notes: "", image: "" },
    { id: 8, name: "Ghost", variety: "Chagoi", length: 43, date: "", status: "alive", notes: "", image: "" },
    { id: 9, name: "Dot", variety: "Ochiba Shigure", length: 39, date: "", status: "alive", notes: "", image: "" },
    { id: 10, name: "Ki Utsuri 2", variety: "Ki Utsuri", length: 47, date: "", status: "alive", notes: "", image: "" },
    { id: 11, name: "Hi Utsuri", variety: "Hi Utsuri", length: 42, date: "", status: "alive", notes: "", image: "" },
    { id: 12, name: "Danté", variety: "Shusui", length: 38, date: "", status: "alive", notes: "", image: "" },
    { id: 13, name: "Shusui", variety: "Shusui", length: 49, date: "", status: "alive", notes: "", image: "" },
    { id: 14, name: "Shiro Muji", variety: "Shiro Muji", length: 28, date: "", status: "alive", notes: "", image: "" },
    { id: 15, name: "Kohaku 1", variety: "Kohaku", length: 32, date: "", status: "alive", notes: "", image: "" },
    { id: 16, name: "Kohaku 2", variety: "Kohaku", length: 29, date: "", status: "alive", notes: "", image: "" },
    { id: 17, name: "Unnamed 2", variety: "-", length: 7, date: "", status: "alive", notes: "", image: "" },
    { id: 18, name: "Asagi 1", variety: "Asagi", length: 6, date: "", status: "alive", notes: "", image: "" },
    { id: 19, name: "Asagi 2", variety: "Asagi", length: 9, date: "", status: "alive", notes: "", image: "" },
    { id: 20, name: "Asagi 3", variety: "Asagi", length: 14, date: "", status: "alive", notes: "", image: "" },
    { id: 21, name: "Orange 1", variety: "Orange", length: 16, date: "", status: "alive", notes: "", image: "" },
    { id: 22, name: "Orange 2", variety: "Orange", length: 45, date: "", status: "alive", notes: "", image: "" },
    { id: 23, name: "Shiro Utsuri 1", variety: "Shiro Utsuri", length: 17, date: "", status: "alive", notes: "", image: "" },
    { id: 24, name: "Perfect Tancho", variety: "Tancho", length: 17, date: "", status: "alive", notes: "", image: "" },
    { id: 25, name: "Tancho 2", variety: "Tancho", length: 50, date: "", status: "alive", notes: "", image: "" },
    { id: 26, name: "Dino", variety: "Goshiki", length: 58, date: "", status: "alive", notes: "", image: "" },
    { id: 27, name: "Goshiki", variety: "Goshiki", length: 11, date: "", status: "alive", notes: "", image: "" },
    { id: 28, name: "Shiro Utsuri 2", variety: "Shiro Utsuri", length: 28, date: "", status: "alive", notes: "", image: "" },
    { id: 29, name: "Princess 2", variety: "Kohaku", length: 27, date: "", status: "alive", notes: "", image: "" },
    { id: 30, name: "Princess 1", variety: "Sanke", length: 47, date: "", status: "alive", notes: "", image: "" },
    { id: 31, name: "Sanke", variety: "Sanke", length: 25, date: "", status: "alive", notes: "", image: "" }
];