// data.js - Your complete koi collection
const initialFishData = [
    { id: 1, name: "Ochiba Shigure", variety: "Ochiba Shigure", length: 43, date: "", status: "alive", notes: "", image: "" },
    { id: 2, name: "Black Nosed Sanke", variety: "Black nosed sanke", length: 38, date: "", status: "alive", notes: "", image: "" },
    { id: 3, name: "Goshiki", variety: "Goshiki", length: 33, date: "", status: "alive", notes: "", image: "" },
    { id: 4, name: "Gin Rin Sanke", variety: "Gin Rin Sanke", length: 45, date: "", status: "alive", notes: "", image: "" },
    { id: 5, name: "Shiro Utsuri", variety: "Shiro Utsuri", length: 60, date: "", status: "deceased", notes: "", image: "" },
    { id: 6, name: "Platinum Ogon", variety: "Platinum Ogon", length: 40, date: "", status: "alive", notes: "", image: "" },
    { id: 7, name: "Gin Rin Sanke 2", variety: "Gin Rin Sanke", length: 46, date: "", status: "alive", notes: "", image: "" },
    { id: 8, name: "Chagoi", variety: "Chagoi", length: 43, date: "", status: "alive", notes: "", image: "" },
    { id: 9, name: "Ochiba Shigure 2", variety: "Ochiba Shigure", length: 39, date: "", status: "alive", notes: "", image: "" },
    { id: 10, name: "Ki Utsuri", variety: "Ki Utsuri", length: 47, date: "", status: "alive", notes: "", image: "" },
    { id: 11, name: "Hi", variety: "Hi Utsuri", length: 42, date: "", status: "alive", notes: "", image: "" },
    { id: 12, name: "Tancho", variety: "-", length: 38, date: "", status: "alive", notes: "", image: "" },
    { id: 13, name: "Shusui", variety: "Shusui", length: 49, date: "", status: "alive", notes: "", image: "" },
    { id: 14, name: "Pearl", variety: "Shiro Muji", length: 28, date: "", status: "deceased", notes: "", image: "" },
    { id: 15, name: "Pumkin", variety: "Kohaku", length: 32, date: "", status: "alive", notes: "", image: "" },
    { id: 16, name: "Two Face", variety: "Kohaku", length: 29, date: "", status: "alive", notes: "", image: "" },
    { id: 17, name: "Ghost", variety: "-", length: 0, date: "", status: "alive", notes: "No length recorded in original sheet", image: "" },
    { id: 18, name: "Asagi 1", variety: "Asagi", length: 7, date: "", status: "alive", notes: "", image: "" },
    { id: 19, name: "Asagi 2", variety: "Asagi", length: 6, date: "", status: "alive", notes: "", image: "" },
    { id: 20, name: "Asagi 3", variety: "Asagi", length: 9, date: "", status: "alive", notes: "", image: "" },
    { id: 21, name: "Orange 1", variety: "Orange", length: 14, date: "", status: "alive", notes: "", image: "" },
    { id: 22, name: "Orange 2", variety: "Orange", length: 16, date: "", status: "alive", notes: "", image: "" },
    { id: 23, name: "Shiro Utsuri 1", variety: "Shiro Utsuri", length: 45, date: "", status: "alive", notes: "", image: "" },
    { id: 24, name: "Perfect Tancho", variety: "Tancho", length: 17, date: "", status: "alive", notes: "", image: "" },
    { id: 25, name: "Tancho 2", variety: "Tancho", length: 17, date: "", status: "alive", notes: "", image: "" },
    { id: 26, name: "Dino", variety: "-", length: 50, date: "", status: "alive", notes: "", image: "" },
    { id: 27, name: "Goshiki 2", variety: "Goshiki", length: 58, date: "", status: "alive", notes: "", image: "" },
    { id: 28, name: "Shiro Utsuri 2", variety: "Shiro Utsuri", length: 11, date: "", status: "alive", notes: "", image: "" },
    { id: 29, name: "Princess 2", variety: "-", length: 28, date: "", status: "alive", notes: "", image: "" },
    { id: 30, name: "Princess 1", variety: "-", length: 27, date: "", status: "alive", notes: "", image: "" },
    { id: 31, name: "Sanke", variety: "Sanke", length: 47, date: "", status: "alive", notes: "", image: "" },
    { id: 32, name: "Dot", variety: "Kohaku", length: 25, date: "", status: "alive", notes: "", image: "" },
    { id: 33, name: "Albino Iridescent Shark 1", variety: "Albino Iridescent Shark", length: 30, date: "", status: "alive", notes: "", image: "" },
    { id: 34, name: "Albino Iridescent Shark 2", variety: "Albino Iridescent Shark", length: 20, date: "", status: "alive", notes: "Slight stomach problem", image: "" },
    { id: 35, name: "Iridescent Shark 1", variety: "Iridescent Shark", length: 12, date: "", status: "alive", notes: "", image: "" },
    { id: 36, name: "Iridescent Shark 2", variety: "Iridescent Shark", length: 14, date: "", status: "alive", notes: "", image: "" }
];
